refactor(fivetran_sdk): improvements in examples
fivetran/fivetran_sdk pull request #46
Opened 2024-06-12 13:01 UTC by fivetran-satvikpatil

Closes https://fivetran.height.app/T-718405

### Description of change
- Added a field missing in VisibilityCondition
- Added example usage of FieldSet

2024-06-18 04:44 UTC, ediril requested changes
This PR should be modifying/using `xxx_v2.proto` files and the examples should also be using the v2 proto files. Instead it is modifying the production proto files. Can we please fix it?

2024-06-18 04:44 UTC, ediril commented on common.proto
> +message DataTypeParams {
This is not in production yet, we shouldn't add it to `common.proto`. It should go into `common_v2.proto`

2024-06-18 04:44 UTC, ediril commented on common.proto
> +  optional DataTypeParams params = 4;
Not in production yet

2024-06-18 04:44 UTC, ediril commented on destination_sdk.proto
>      repeated DataTypeMappingEntry data_type_mappings = 1;
In production, we only have `BatchFileFormat batch_file_format = 1;`

2024-06-18 04:44 UTC, ediril commented on destination_sdk.proto
>  message DataTypeMappingEntry {
This is not in production yet

2024-06-20 15:37 UTC, fivetran-satvikpatil commented
@ediril I have made these changes in this PR: https://github.com/fivetran/fivetran_sdk/pull/50. 
As it was dependent on Manju's PR. I am closing this PR.

2024-06-20 15:37 UTC, closed without merging