doc(Fivetran_sdk): Doc changes required for parquet support in destination tester
fivetran/fivetran_sdk pull request #53
Opened 2024-06-24 09:36 UTC by fivetran-satvikpatil

Closes https://fivetran.height.app/T-720440

2024-06-25 03:58 UTC, ediril requested changes

2024-06-25 03:58 UTC, ediril commented on tools/destination-tester/README.md
> +We support generating batch files in both CSV and Parquet formats. By default, tester uses CSV for batch file generation, but you can specify the desired format using this CLI argument.
What would they type in to specify using parquet?

Also, I don't see the code for this option in `engineering` repo, under v2 destination tester. Where is it?

2024-06-25 04:00 UTC, ediril requested changes

2024-06-25 04:01 UTC, ediril approved these changes

2025-03-03 18:13 UTC, closed without merging

2025-03-03 18:13 UTC, fivetran-satvikpatil commented
We have already done this change, closing this PR.