doc(partner_sdk): Alter Table operation guidelines
fivetran/fivetran_sdk pull request #71
Opened 2024-10-09 22:29 UTC by fivetran-rishabhghosh

Add guidelines for Alter Table operation

2024-10-14 10:41 UTC, varundhall approved these changes

2024-10-14 14:49 UTC, shivangisingh172 approved these changes

2024-10-14 17:37 UTC, fivetran-dejantucakov requested changes
@fivetran-rishabhghosh Please see suggestions and comments.

2024-10-14 17:37 UTC, fivetran-dejantucakov commented on development-guide.md
> +- This operation should exercise change of primary key columns, addition of columns, change of data types, etc.
@fivetran-rishabhghosh Ending with etc. is very vague. Can you provide more specific operations?

2024-10-14 17:37 UTC, fivetran-dejantucakov commented on development-guide.md
> +- This operation should exercise change of primary key columns, addition of columns, change of data types, etc.
```suggestion
- This operation should perform changes to primary key columns and data types, column additions, (INSERT OTHER)
```

2024-10-14 17:37 UTC, fivetran-dejantucakov commented on development-guide.md
> +- However, this operation should not drop any columns even if the alter table request has a table with a different set of columns. Dropping of columns could lead to unexpected data loss for customers
```suggestion
- However, this operation should not drop any columns even if the AlterTable request has a table with a different set of columns. Dropping columns could lead to unexpected customer data loss and is against Fivetran's general approach to data movement.
```

2024-10-15 11:59 UTC, fivetran-rishabhghosh commented
@fivetran-dejantucakov Updated

2024-10-15 12:31 UTC, fivetran-dejantucakov commented on development-guide.md
> +- However, this operation should not drop any columns even if the AlterTable request has a table with a different set of columns. Dropping columns could lead to unexpected customer data loss and is a
```suggestion
- This operation should be used for changing primary key columns, adding columns, and changing data types. 
- However, this operation should not drop any columns even if the `AlterTable` request has a table with a different set of columns. Dropping columns could lead to unexpected customer data loss and is against Fivetran's general approach to data movement.
```

2024-10-15 12:31 UTC, fivetran-dejantucakov requested changes
@fivetran-rishabhghosh Please see suggestions.

2024-10-15 13:27 UTC, fivetran-dejantucakov approved these changes
@fivetran-rishabhghosh Approved, tnx!

2024-10-15 13:28 UTC, merged

2024-10-15 14:37 UTC, alsnkline commented on development-guide.md
> +- However, this operation should not drop any columns even if the `AlterTable` request has a table with a different set of columns. Dropping columns could lead to unexpected customer data loss and is
This doesn't say what they should do. i'd also love to link to a doc that describes our policy/what we usually do - ie not dropping columns/deleting data - but I didn't just find a suitable link.

eg 'this operation should not drop any columns even if the 'AlterTabel' request has a table with a different set of columns. Fivetran's approach to data movement is to leave such columns in a customer's warehouse with no additional data populating to provide the customer control and choice on timing for removal. Dropping columns can lead to unexpected customer data loss.